# Generated by Django 6.0.6 on 2026-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='chemical_type',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.CharField(default='Safe', max_length=50),
        ),
    ]
