# Generated by Django 6.0.6 on 2026-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_sensordata_chemical_type_sensordata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='chemical_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
