# Generated by Django 6.0.6 on 2026-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_sensordata_chemical_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_limit', models.FloatField(default=35.0)),
                ('hum_limit', models.FloatField(default=70.0)),
            ],
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='chemical_type',
            new_name='chemical',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='temperature',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='timestamp',
            new_name='time',
        ),
    ]
